language: python

python:
    - "3.6"
script:
    - pip install parameterized
    - coverage run test_partida.py
    -coverage run -a test_ahorcado.py

install:
    - pip install -r requirements.txt

after_success:
    - coveralls